"""Create batch_states table

Revision ID: c5b94b905d26
Revises: 
Create Date: 2024-11-29 08:47:31.402932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5b94b905d26'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_states',
    sa.Column('batch_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=255),  nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True),  nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True),  nullable=False),
    sa.Column('current_page', sa.INTEGER(), nullable=False),
    sa.Column('last_search_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('total_records', sa.INTEGER(), nullable=True),
    sa.Column('fetched_records', sa.INTEGER(), nullable=True),
    sa.Column('target_pause_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('initial_start_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('Asia/Bangkok'::text, now())"), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('Asia/Bangkok'::text, now())"), nullable=False),
    sa.PrimaryKeyConstraint('batch_id', 'run_id', name='batch_states_pkey')
    )
    op.create_index('idx_batch_states_updated_at', 'batch_states', ['updated_at'], unique=False)
    op.create_index('idx_batch_states_status', 'batch_states', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_batch_states_status', table_name='batch_states')
    op.drop_index('idx_batch_states_updated_at', table_name='batch_states')
    op.drop_table('batch_states')
    # ### end Alembic commands ###